package foxparade.command.logic.loot.constants

class LootConstants {
    companion object {

        val MYTHIC_MODIFIERS: List<String> = listOf(
            "Angelic",
            "Elven",
            "Birthday",
            "Halloween",
            "Maple Syrup-y"
        )

        val RARE_MODIFIERS: List<String> = listOf(
            "Haunted",
            "Enchanted",
            "Mysterious",
            "Mystical",
            "Sensual",
            "Mermaid",
        )

        val NORMAL_MODIFIERS: List<String> = listOf(
            "Baby",
            "Beautiful",
            "Bedazzled",
            "Casual",
            "Charming",
            "Colourful",
            "Creepy",
            "Cute",
            "Delicate",
            "Edgy",
            "Elegant",
            "Embroidered",
            "Fairytale",
            "Fashionable",
            "Floral",
            "Fluffy",
            "Frilly",
            "Girly",
            "Gorgeous",
            "Graceful",
            "Kawaii",
            "Lacy",
            "Leather",
            "Long",
            "Oversized",
            "Plaid",
            "Ruffled",
            "Sakura-patterned",
            "Sheer",
            "Short",
            "Sparkling",
            "Spooky",
            "Sunflower-patterned",
            "Unique",
            "Vintage",
            "Starry",
            "Cloudy",
        )

        val BAD_MODIFIERS: List<String> = listOf(
            "Broken",
            "Creepy",
            "Furry",
            "Loose",
            "Mismatched",
            "Mouldy",
            "Overpriced",
            "Stained",
            "Sticky",
            "Stinky",
            "Tattered",
            "Wet",
            "Yellowed",
            "Chewed-on",
        )

        val BASIC_COLORS: List<String> = listOf(
            "Pastel",
            "Red",
            "Blue",
            "Green",
            "Yellow",
            "Orange",
            "Purple",
            "Pink",
            "Brown",
            "Black",
            "White",
            "Grey",
            "Pearlescent",
        )

        val ANIMAL_COLORS: List<String> = listOf(
            "Froggy",
            "Bear",
            "Cat",
            "Puppy",
            "Fox",
            "Mouse",
            "Hamster",
            "Wolf",
            "Tanuki",
            "Bunny",
        )

        val BODY_COLORS: List<String> = listOf(
            "Tan",
            "Flesh",
            "Semi-white",
            "Tawny"
        )

        val COLORABLE_TOYS: List<String> = listOf(
            "Outfit",
            "Wig",
            "Eyes",
            "Shoes",
            "Hair Clips",
            "Doll Bag",
            "Necklace",
            "Glasses",
            "Headphones",
            "Pacifier",
            "Hat",
            "Socks",
            "Lingerie",
            "Swimsuit",
            "Kimono",
            "School Uniform",
            "Lolita Dress",
            "Punk Outfit",
            "Jirai-kei Outfit",
            "Fantasy Outfit",
            "Maid Outfit",
            "Nurse Uniform",
            "Miko Outfit",
            "Handbag",
            "Backpack",
            "Umbrella",
            "Raincoat",
            "Boots",
            "Roller Skates",
            "Crocs",
            "Pyjamas",
            "Panties",
            "Skirt",
            "Shorts",
            "Overalls",
            "Tutu",
            "Beret",
            "Uniform",
            "Shirt",
            "Mini Skirt",
            "Cheerleader Outfit",
            "Ita-bag",
            "Hoodie",
            "Sweater",
            "Apron",
            "Bikini",
            "High Heels",
            "Stockings",
            "Platform Shoes",
            "Choker",
            "Garters",
        )

        val ANIMAL_TOYS: List<String> = listOf(
            "Tail",
            "Ears",
            "Paws",
            "Hat",
            "Socks",
            "Lingerie",
            "School Uniform",
            "Lolita Dress",
            "Punk Outfit",
            "Maid Outfit",
            "Nurse Uniform",
            "Miko Outfit",
            "Handbag",
            "Backpack",
            "Umbrella",
            "Raincoat",
            "Boots",
            "Shoes",
            "Onesie",
            "Roller skates",
            "Pyjamas",
            "Panties",
            "Overalls",
            "Uniform",
        )

        val BODY_TOYS: List<String> = listOf(
            "Mini Body",
            "Mini Head",
            "Sister Head",
            "Sister Body",
            "Manicured Hands",
        )
    }
}